spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /data-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
